apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxpod
spec:
  selector:
    matchLabels:
      app: nginxpod
  template:
    metadata:
      labels:
        app: nginxpod
    spec:
      containers:
      - name: nginxpod
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
